name: Diep Build Cache

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
